"""
Themes for Phantom - Color schemes
"""

from colorama import Fore, Back, Style

THEMES = {
    "cyber": {
        "name": "Cyber",
        "primary": Fore.CYAN,
        "secondary": Fore.CYAN,
        "accent": Fore.CYAN + Style.BRIGHT,
        "success": Fore.CYAN,
        "error": Fore.CYAN,
        "warning": Fore.CYAN,
        "info": Fore.CYAN,
        "dim": Fore.CYAN + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "matrix": {
        "name": "Matrix",
        "primary": Fore.GREEN,
        "secondary": Fore.GREEN,
        "accent": Fore.GREEN + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.GREEN,
        "warning": Fore.GREEN,
        "info": Fore.GREEN,
        "dim": Fore.GREEN + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "crystal": {
        "name": "Crystal",
        "primary": Fore.CYAN,
        "secondary": Fore.WHITE,
        "accent": Fore.WHITE + Style.BRIGHT,
        "success": Fore.CYAN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.WHITE,
        "dim": Fore.CYAN + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "embers": {
        "name": "Embers",
        "primary": Fore.RED,
        "secondary": Fore.YELLOW,
        "accent": Fore.YELLOW + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.RED,
        "dim": Fore.RED + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "ocean": {
        "name": "Ocean",
        "primary": Fore.BLUE,
        "secondary": Fore.CYAN,
        "accent": Fore.CYAN + Style.BRIGHT,
        "success": Fore.BLUE,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.CYAN,
        "dim": Fore.BLUE + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "neon": {
        "name": "Neon",
        "primary": Fore.MAGENTA,
        "secondary": Fore.CYAN,
        "accent": Fore.MAGENTA + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.CYAN,
        "dim": Fore.MAGENTA + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "gold": {
        "name": "Gold",
        "primary": Fore.YELLOW,
        "secondary": Fore.YELLOW,
        "accent": Fore.YELLOW + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.WHITE,
        "dim": Fore.YELLOW + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "ice": {
        "name": "Ice",
        "primary": Fore.CYAN,
        "secondary": Fore.WHITE,
        "accent": Fore.WHITE + Style.BRIGHT,
        "success": Fore.CYAN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.WHITE,
        "dim": Fore.CYAN + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "midnight": {
        "name": "Midnight",
        "primary": Fore.BLUE,
        "secondary": Fore.MAGENTA,
        "accent": Fore.MAGENTA + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.BLUE,
        "dim": Fore.BLUE + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "sunset": {
        "name": "Sunset",
        "primary": Fore.MAGENTA,
        "secondary": Fore.RED,
        "accent": Fore.YELLOW + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.MAGENTA,
        "dim": Fore.MAGENTA + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "ghost": {
        "name": "Ghost",
        "primary": Fore.WHITE,
        "secondary": Fore.WHITE,
        "accent": Fore.WHITE + Style.BRIGHT,
        "success": Fore.WHITE,
        "error": Fore.WHITE,
        "warning": Fore.WHITE,
        "info": Fore.WHITE,
        "dim": Fore.WHITE + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "plasma": {
        "name": "Plasma",
        "primary": Fore.MAGENTA,
        "secondary": Fore.CYAN,
        "accent": Fore.MAGENTA + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.MAGENTA,
        "dim": Fore.MAGENTA + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "ruby": {
        "name": "Ruby",
        "primary": Fore.RED,
        "secondary": Fore.RED,
        "accent": Fore.RED + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.RED,
        "dim": Fore.RED + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "emerald": {
        "name": "Emerald",
        "primary": Fore.GREEN,
        "secondary": Fore.GREEN,
        "accent": Fore.GREEN + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.GREEN,
        "dim": Fore.GREEN + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    },
    "sapphire": {
        "name": "Sapphire",
        "primary": Fore.BLUE,
        "secondary": Fore.BLUE,
        "accent": Fore.BLUE + Style.BRIGHT,
        "success": Fore.GREEN,
        "error": Fore.RED,
        "warning": Fore.YELLOW,
        "info": Fore.BLUE,
        "dim": Fore.BLUE + Style.DIM,
        "bright": Style.BRIGHT,
        "reset": Fore.RESET,
        "bg": Back.BLACK,
    }
}